# Generated by Django 5.0.6 on 2024-06-25 07:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0002_orderplaced'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Chart',
            new_name='Cart',
        ),
    ]
